In [2]:
import numpy as np
from numpy import genfromtxt

In [3]:
data = genfromtxt('bank_note_data.txt', delimiter=',')

In [4]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [5]:
labels = data[:,4]

In [6]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [7]:
features = data[:,0:4]

In [8]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [9]:
X = features
y = labels

In [10]:
# splitting testing data and training data from dataset
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

In [12]:
len(X)

1372

In [13]:
len(X_train)

919

In [14]:
len(X_test)

453

In [15]:
# for same range data
from sklearn.preprocessing import MinMaxScaler

In [16]:
scaler_object = MinMaxScaler()

In [17]:
scaler_object.fit(X_train)

MinMaxScaler()

In [18]:
scaled_X_train = scaler_object.transform(X_train)

In [19]:
scaled_X_test = scaler_object.transform(X_test)

In [20]:
scaled_X_train.max()

1.0000000000000002

In [21]:
scaled_X_train.min()

0.0

In [22]:
from keras.models import Sequential
from keras.layers import Dense

In [23]:
model = Sequential()
model.add(Dense(4, input_dim=4, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [24]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics = ['accuracy'])

In [25]:
model.fit(scaled_X_train, y_train, epochs=50, verbose=2)

Epoch 1/50
29/29 - 0s - loss: 0.6868 - accuracy: 0.5495
Epoch 2/50
29/29 - 0s - loss: 0.6842 - accuracy: 0.5495
Epoch 3/50
29/29 - 0s - loss: 0.6796 - accuracy: 0.5495
Epoch 4/50
29/29 - 0s - loss: 0.6738 - accuracy: 0.5517
Epoch 5/50
29/29 - 0s - loss: 0.6684 - accuracy: 0.5713
Epoch 6/50
29/29 - 0s - loss: 0.6624 - accuracy: 0.6007
Epoch 7/50
29/29 - 0s - loss: 0.6549 - accuracy: 0.6300
Epoch 8/50
29/29 - 0s - loss: 0.6455 - accuracy: 0.6561
Epoch 9/50
29/29 - 0s - loss: 0.6351 - accuracy: 0.6681
Epoch 10/50
29/29 - 0s - loss: 0.6223 - accuracy: 0.6725
Epoch 11/50
29/29 - 0s - loss: 0.6081 - accuracy: 0.6714
Epoch 12/50
29/29 - 0s - loss: 0.5940 - accuracy: 0.6877
Epoch 13/50
29/29 - 0s - loss: 0.5793 - accuracy: 0.7008
Epoch 14/50
29/29 - 0s - loss: 0.5647 - accuracy: 0.7258
Epoch 15/50
29/29 - 0s - loss: 0.5501 - accuracy: 0.7367
Epoch 16/50
29/29 - 0s - loss: 0.5355 - accuracy: 0.7345
Epoch 17/50
29/29 - 0s - loss: 0.5210 - accuracy: 0.7519
Epoch 18/50
29/29 - 0s - loss: 0.5075 - 

In [27]:
#model.predict_classes(scaled_X_test)

In [28]:
model.metrics_names

['loss', 'accuracy']

In [29]:
from sklearn.metrics import confusion_matrix, classification_report

In [30]:
# predicting the test set results
predictions = model.predict_classes(scaled_X_test)

In [31]:
confusion_matrix(y_test, predictions)

array([[255,   2],
       [ 17, 179]], dtype=int64)

In [33]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.94      0.99      0.96       257
         1.0       0.99      0.91      0.95       196

    accuracy                           0.96       453
   macro avg       0.96      0.95      0.96       453
weighted avg       0.96      0.96      0.96       453



In [34]:
# saving the model
model.save('mymodel.h5')

In [35]:
from keras.models import load_model

In [36]:
# loading the model
newmodel = load_model('mymodel.h5')

In [37]:
newmodel.predict_classes(scaled_X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
    